"""Create_satellite_tables

Revision ID: 30f1d6f25759
Revises: 8ce49bfd8a9c
Create Date: 2025-07-01 04:26:34.726183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f1d6f25759'
down_revision: Union[str, Sequence[str], None] = '8ce49bfd8a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planet_collections_id'), 'planet_collections', ['id'], unique=False)
    op.create_table('satellites',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('region_url', sa.String(), nullable=False),
    sa.Column('is_catalogue_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('indices',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('evalscript', sa.String(), nullable=False),
    sa.Column('statistical_evalscript', sa.String(), nullable=True),
    sa.Column('satellite', sa.String(), nullable=False),
    sa.Column('legend', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['satellite'], ['satellites.name'], ),
    sa.PrimaryKeyConstraint('name', 'satellite')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indices')
    op.drop_table('satellites')
    op.drop_index(op.f('ix_planet_collections_id'), table_name='planet_collections')
    op.drop_table('planet_collections')
    # ### end Alembic commands ###
