"""add_cloud_cover

Revision ID: 4810da1cc3e3
Revises: 9765b1bc5b2f
Create Date: 2025-07-04 22:59:05.740671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4810da1cc3e3'
down_revision: Union[str, Sequence[str], None] = '9765b1bc5b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('satellites', sa.Column('cloud_cover', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('satellites', 'cloud_cover')
    # ### end Alembic commands ###