"""Adding name to farm model

Revision ID: 5785f569473e
Revises: bbf0e6c0a9a3
Create Date: 2025-07-03 11:49:13.466235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5785f569473e'
down_revision: Union[str, Sequence[str], None] = 'bbf0e6c0a9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'name')
    # ### end Alembic commands ###
