"""Create_farm_name_column

Revision ID: 628f1f2829a8
Revises: f0d9da385cf2
Create Date: 2025-06-30 06:45:55.321329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628f1f2829a8'
down_revision: Union[str, Sequence[str], None] = 'f0d9da385cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('farm_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'farm_name')
    # ### end Alembic commands ###
