"""Updated user auth models and roles

Revision ID: 8ce49bfd8a9c
Revises: 628f1f2829a8
Create Date: 2025-06-30 21:01:23.941710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ce49bfd8a9c'
down_revision: Union[str, Sequence[str], None] = '628f1f2829a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kvks_id'), table_name='kvks')
    op.drop_table('kvks')
    op.alter_column('farm', 'kvk_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(op.f('farm_kvk_id_fkey'), 'farm', type_='foreignkey')
    op.create_foreign_key(None, 'farm', 'users', ['kvk_id'], ['id'])
    op.drop_column('farm', 'kvk')
    op.drop_column('farm', 'farmer_name')
    op.add_column('users', sa.Column('kvk_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('director_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('established_year', sa.String(length=4), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['kvk_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'established_year')
    op.drop_column('users', 'director_name')
    op.drop_column('users', 'pincode')
    op.drop_column('users', 'address')
    op.drop_column('users', 'state')
    op.drop_column('users', 'district')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'kvk_id')
    op.add_column('farm', sa.Column('farmer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('farm', sa.Column('kvk', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'farm', type_='foreignkey')
    op.create_foreign_key(op.f('farm_kvk_id_fkey'), 'farm', 'kvks', ['kvk_id'], ['id'])
    op.alter_column('farm', 'kvk_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('kvks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kvk_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('kvk_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('director_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('established_year', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('blocked_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('kvks_pkey')),
    sa.UniqueConstraint('email', name=op.f('kvks_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('kvk_code', name=op.f('kvks_kvk_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_kvks_id'), 'kvks', ['id'], unique=False)
    # ### end Alembic commands ###
