"""updated kvk to parent in user table

Revision ID: 9765b1bc5b2f
Revises: 1d73843703b7
Create Date: 2025-07-03 13:16:34.193177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '9765b1bc5b2f'
down_revision: Union[str, Sequence[str], None] = '1d73843703b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('farm', 'center',
               existing_type=Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    op.create_geospatial_index('idx_farm_center', 'farm', ['center'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.add_column('users', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('users_kvk_id_fkey1'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['parent_id'], ['id'])
    op.drop_column('users', 'kvk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kvk_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_kvk_id_fkey1'), 'users', 'users', ['kvk_id'], ['id'])
    op.drop_column('users', 'parent_id')
    op.drop_geospatial_index('idx_farm_center', table_name='farm', postgresql_using='gist', column_name='center')
    op.alter_column('farm', 'center',
               existing_type=Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'),
               type_=Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
    # ### end Alembic commands ###
