"""Add soil nutrient fields to Farm

Revision ID: a1c8a72e3242
Revises: dacb924607b2
Create Date: 2025-07-03 11:07:48.700289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1c8a72e3242'
down_revision: Union[str, Sequence[str], None] = 'dacb924607b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('carbon_organic_gperkg', sa.Float(), nullable=True))
    op.add_column('farm', sa.Column('nitrogen_gperkg', sa.Float(), nullable=True))
    op.add_column('farm', sa.Column('ph', sa.Float(), nullable=True))
    op.add_column('farm', sa.Column('phosphorus_ppm', sa.Float(), nullable=True))
    op.add_column('farm', sa.Column('potassium_ppm', sa.Float(), nullable=True))
    op.alter_column('farm', 'bbox',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('farm', 'bbox',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('farm', 'potassium_ppm')
    op.drop_column('farm', 'phosphorus_ppm')
    op.drop_column('farm', 'ph')
    op.drop_column('farm', 'nitrogen_gperkg')
    op.drop_column('farm', 'carbon_organic_gperkg')
    # ### end Alembic commands ###
