"""Add soft delete to farm

Revision ID: c902937f1dec
Revises: 4810da1cc3e3
Create Date: 2025-07-11 20:43:29.266940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c902937f1dec'
down_revision: Union[str, Sequence[str], None] = '4810da1cc3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('deleted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'deleted')
    # ### end Alembic commands ###
