"""Create market, user, role, kvk, farm tables

Revision ID: f0d9da385cf2
Revises: 
Create Date: 2025-06-30 05:08:31.455814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'f0d9da385cf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kvks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kvk_name', sa.String(length=255), nullable=False),
    sa.Column('kvk_code', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('director_name', sa.String(length=255), nullable=True),
    sa.Column('established_year', sa.String(length=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('kvk_code')
    )
    op.create_index(op.f('ix_kvks_id'), 'kvks', ['id'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=100), nullable=True),
    sa.Column('commodity', sa.String(length=100), nullable=True),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('modal_price', sa.Float(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'district', 'market', 'commodity', 'variety', 'grade', 'arrival_date', name='uq_market_unique')
    )
    op.create_index('idx_arrival_date', 'market_data', ['arrival_date'], unique=False)
    op.create_index('idx_combo', 'market_data', ['state', 'district', 'market', 'commodity', 'variety', 'grade'], unique=False)
    op.create_index('idx_commodity', 'market_data', ['commodity'], unique=False)
    op.create_index('idx_district', 'market_data', ['district'], unique=False)
    op.create_index('idx_state', 'market_data', ['state'], unique=False)
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_geospatial_table('farm',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kvk_id', sa.Integer(), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='POLYGON', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('center', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=True),
    sa.Column('ai_yield', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('kvk', sa.String(length=255), nullable=True),
    sa.Column('ndvi', sa.Float(), nullable=True),
    sa.Column('farmer_name', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['kvk_id'], ['kvks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_farm_center', 'farm', ['center'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_farm_geometry', 'farm', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_farm_id'), 'farm', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_id'), table_name='farm')
    op.drop_geospatial_index('idx_farm_geometry', table_name='farm', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_index('idx_farm_center', table_name='farm', postgresql_using='gist', column_name='center')
    op.drop_geospatial_table('farm')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_index('idx_state', table_name='market_data')
    op.drop_index('idx_district', table_name='market_data')
    op.drop_index('idx_commodity', table_name='market_data')
    op.drop_index('idx_combo', table_name='market_data')
    op.drop_index('idx_arrival_date', table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_kvks_id'), table_name='kvks')
    op.drop_table('kvks')
    # ### end Alembic commands ###
