"""Add sowing_date to Farm

Revision ID: f0e3d74ff5c8
Revises: 5785f569473e
Create Date: 2025-07-03 12:19:39.095427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e3d74ff5c8'
down_revision: Union[str, Sequence[str], None] = '5785f569473e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('sowing_date', sa.Date(), nullable=True))
    op.drop_column('farm', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('farm', 'sowing_date')
    # ### end Alembic commands ###
